repos:
-   repo: local
    hooks:
    -   id: f-dotfiles
        name: f-dotfiles
        description: README.md packages listings injector
        entry: f-dotfiles.py
        language: script
        always_run: true
        pass_filenames: false
